import {
  Sparkles,
  Code,
  PenTool,
  Presentation,
  Cpu,
  Zap,
  Layout,
  Palette,
  Search,
  Terminal,
  Bot,
  Workflow,
  FileText,
  GitGraph,
  Mail,
  User,
  BookOpen,
  MessageSquare,
  Briefcase,
  Brain,
  Smartphone,
  Globe,
  Server,
  Layers,
  GraduationCap,
  Image,
  Video,
  Music,
  Mic,
  Camera,
  Database,
  Cloud,
  Shield,
  Lock,
  Link,
  ExternalLink,
  Settings,
} from "lucide-react";
import {
  SiOpenai,
  SiAnthropic,
  SiNotion,
  SiGoogle,
  SiFigma,
} from "react-icons/si";
import {
  CursorIcon,
  GammaIcon,
  GensparkIcon,
  PerplexityIcon,
  MidjourneyIcon,
} from "../components/CustomIcons";

export const ICON_MAP = {
  // Custom Icons
  CursorIcon: CursorIcon,
  GammaIcon: GammaIcon,
  GensparkIcon: GensparkIcon,
  PerplexityIcon: PerplexityIcon,
  MidjourneyIcon: MidjourneyIcon,

  // Simple Icons
  SiOpenai: SiOpenai,
  SiAnthropic: SiAnthropic,
  SiNotion: SiNotion,
  SiGoogle: SiGoogle,
  SiFigma: SiFigma,

  // Lucide
  Sparkles: Sparkles,
  Code: Code,
  PenTool: PenTool,
  Presentation: Presentation,
  Terminal: Terminal,
  Bot: Bot,
  Workflow: Workflow,
  FileText: FileText,
  GitGraph: GitGraph,
  Mail: Mail,
  BookOpen: BookOpen,
  Search: Search,
  Zap: Zap,
  Layout: Layout,
  Cpu: Cpu,
  Palette: Palette,
  // Added for Academy
  Smartphone: Smartphone,
  Globe: Globe,
  Server: Server,
  Layers: Layers,
  GraduationCap: GraduationCap,
  Briefcase: Briefcase,
  MessageSquare: MessageSquare,
  Brain: Brain,
  User: User,
  // New Additions
  Image: Image,
  Video: Video,
  Music: Music,
  Mic: Mic,
  Camera: Camera,
  Database: Database,
  Cloud: Cloud,
  Shield: Shield,
  Lock: Lock,
  Link: Link,
  ExternalLink: ExternalLink,
  Settings: Settings,
};
